#       $NetBSD: Makefile,v 1.3 2009/11/05 15:08:19 stacktic Exp $
#       @(#)Makefile    8.1 (Berkeley) 6/2/93


PROG=   	fsu_mknod
.PATH:		../mknod
SRCS=   	mknod.c pack_dev.c
MAN=		fsu_mknod.1

.include <bsd.prog.mk>
