#       $NetBSD: Makefile,v 1.2 2009/03/24 15:14:24 stacktic Exp $
#       @(#)Makefile    8.1 (Berkeley) 6/2/93


PROG=   	fsu_mkfifo
.PATH:		../mkfifo
SRCS=   	mkfifo.c
MAN=		fsu_mkfifo.1

.include "${.CURDIR}/../../Makefile.fsu"
.include <bsd.prog.mk>
